name = 'cloudflare-docker-proxy-new'
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[build]
command = "npm run build"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://ghcr.io"
CUSTOM_DOMAIN = "dawngs.top"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
    { pattern = "ghcr.dawngs.top", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = "https://ghcr.io"

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.dawngs.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = "https://ghcr.io"
