name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

main = "src/index.ts"

[assets]
directory = "./dist"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://ghcr.io"
CUSTOM_DOMAIN = "dawngs.top"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
    { pattern = "ghcr.dawngs.top", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.dawngs.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
